name: React Resume
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -f

      - name: Build the React app
        run: npm run build

      - name: Upload build directory
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

  deploy:
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://morieskie.github.io/react-resume"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REACT_RESUME_PAT }}
          publish_dir: ./build

      # - name: Check build directory contents
      #   run: ls -l ./build
