name: React Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -f

      - name: Build the React app
        run: |
          npm run build
          if [ ! -d "./build" ]; then
            echo "Build directory not found!"
            exit 1
          fi

      - name: List directory contents
        run: |
          echo "Listing root directory:"
          ls -l
          # echo "Listing project directory:"
          # ls -l ./react-resume
          # echo "Listing build directory (if exists):"
          # ls -l ./react-resume/build


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REACT_RESUME_PAT }}
          publish_dir: ./build

  # deploy:
  #   needs: build
  #   permissions:
  #     contents: write
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: 'https://morieskie.github.io/react-resume'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.REACT_RESUME_PAT }}
  #         publish_dir: ./build
